version: '3.8'

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pointstorm-pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv=PB_ENCRYPTION_KEY
    environment:
      - PB_ENCRYPTION_KEY=your-32-char-encryption-key-here
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - ./pocketbase/migrations:/pb_migrations
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pocketbase_data:
    driver: local